name: continuous integrate
on: push
  branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
      - name: setup java
        uses: actions/setup-java@v1
          with:
            java-version: '1.8'
      - name checkout
        uses: actions/checkout@v1
          with:
            fetch-depth: 1
