name: pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    - name: setup java
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
